### ISSUE TITLE
Question on app data location

### ISSUE THREAD

**Issue by ghost** [tea-note/tea-note.github.io#2]
Hi I really like the TeaNote app, but before using it as my note taking app, may I know where are the notes data kept on a Mac? Are they synchronised to any cloud server? Can I customise the document location to any local folder? Thanks.

**Comment by tea-note** [comment]
Hi, Thank you for considering us as your note taking app.
We use electron to build our app and all data will save to your local disk. 
All data will save to index-db and will not sync to any cloud server.
Now, users can't customise their document location, but we consider adding this feature.
