### ISSUE TITLE
导出功能bug

### ISSUE THREAD

**Issue by NoUltimate** [tea-note/tea-note.github.io#3]
- 笔记包含tag或者wiki的时候导出预览有乱码，点击导出为word和文本格式后打开发现无法正常显示tag和wiki
- 顺便问下有没有开发ipad端以及云同步的计划
![image](https://user-images.githubusercontent.com/32738861/127632305-7d550597-6a41-4bf9-9820-029cd7c2d628.png)

**Comment by tea-note** [comment]
您好，非常感谢您的反馈。我们已经确认了这个bug，并且在2.2.0版本中做了修复，您可以安装最新版本的Tea Note。

**Comment by tea-note** [comment]
非常感谢您对我们的产品的反馈，我们决定给您提供一个月的PRO版本使用，您可以关注《迅迅的时间笔记》微信公众号，后台回复“促销”获得最新App store的免费促销码
![](https://xunxun2hei.oss-cn-shanghai.aliyuncs.com/system/qrcode_for_gh_d14fa0fe79e4_258.jpg)
