### ISSUE TITLE
笔记本markdown问题

### ISSUE THREAD

**Issue by NoUltimate** [tea-note/tea-note.github.io#5]
1. 无序和有序列表
初始状态
![image](https://user-images.githubusercontent.com/32738861/130929360-9cbf9529-9831-47cd-a826-4ee5b19a8ef7.png)
如果在红框处使用删除按钮（即换行后马上删除），上一行会下移
![image](https://user-images.githubusercontent.com/32738861/130929559-9871f227-25a5-4849-9db1-0bff9d89ebc0.png)

2.使用/进行快速插入的时候，文本不会消失
例如我使用了/code后找到代码块回车后，/code并不会消失
![image](https://user-images.githubusercontent.com/32738861/130929688-98902b4b-6a28-4746-8096-cdc488312dcd.png)

3.希望能够增加一个代码行(``)的markdown语法，每次代码块个人觉得太占位置了

**Comment by xunxun2hei** [comment]
好的，相关问题我这边收下了，会尽快安排修复

**Comment by lvshuncn** [comment]
0908发布3.0.0版本，已修复上述问题
